In [41]:
import numpy as np
n=int(input("Enter the size of the square matrix (n): "))
print(f"Enter the {n}*{n} matrix row by row (Space Aeparated): ")
A=[]
for i in range(n):
    row=list(map(float, input(f"Row {i+1}: ").split()))
    A.append(row)
print(A)

Enter the size of the square matrix (n):  2 


Enter the 2*2 matrix row by row (Space Aeparated): 


Row 1:  2 1
Row 2:  1 2


[[2.0, 1.0], [1.0, 2.0]]


In [4]:
# split()
# Splits the input string into a list of substrings based on spaces.
# "1 2 3".split() → ["1", "2", "3"]
# map(float, ["1", "2", "3"])
# Applies the float() function to each element of the list.
# "1" → 1.0, "2" → 2.0, "3" → 3.0
# Now we get a map object containing [1.0, 2.0, 3.0].
# list(...)
# Converts the map object into a list.
# Final result: [1.0, 2.0, 3.0]

In [42]:
A=np.array(A)
print(A)

[[2. 1.]
 [1. 2.]]


In [43]:
eigenvalues, eignvectors=np.linalg.eig(A)
print(eigenvalues)

[3. 1.]


In [44]:
print(eignvectors)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [45]:
Lambda=np.diag(eigenvalues)
print(Lambda)

[[3. 0.]
 [0. 1.]]


In [46]:
Q=eigenvectors
print(Q)

[[-0.76231552 -0.51853163]
 [ 0.64720557 -0.85505845]]


In [47]:
Q_Lambda=Q.T
print(Q_Lambda)

[[-0.76231552  0.64720557]
 [-0.51853163 -0.85505845]]


In [48]:
A_reconstructed=Q@Lambda@Q_Lambda

In [49]:
print(A_reconstructed)

[[ 2.0122499 -1.0367497]
 [-1.0367497  1.9877501]]
